#!/usr/bin/env python3
"""Check bilingual README consistency between README.md and README.zh-CN.md.

Uses only the Python standard library.  Exits with code 0 and prints
``BILINGUAL_README_CONSISTENCY_PASSED`` when all checks succeed.
"""

import re
import sys
from collections import Counter
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
EN_PATH = PROJECT / "README.md"
ZH_PATH = PROJECT / "README.zh-CN.md"

# Language-switch links are allowed to differ
LANGUAGE_LINKS = {"README.md", "README.zh-CN.md", "./README.md", "./README.zh-CN.md"}

# Sync markers that are not followed by a heading (e.g. language nav)
NON_HEADING_MARKERS = {"sync:language"}

# Common mojibake fragments (generated by wrong encoding)
MOJIBAKE_FRAGMENTS = [
    "闁",
    "闂",
    "锟",
    "鏁",
    "�",  # U+FFFD replacement character
    "脙",
    "脛",
    "脙炉",
    "脙麓",
    "忙",
    "聼",
    "猫",
    "麓",  # common UTF-8 interpreted as Latin-1, etc.
]


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------


def _fence_header(line: str) -> str:
    """Return the language tag of a fenced-code-block opener, lowercased."""
    stripped = line.strip()
    if stripped.startswith("```"):
        return stripped[3:].strip().lower()
    return ""


def _is_fence_opener(line: str) -> bool:
    return line.strip().startswith("```")


def _is_fence_closer(line: str) -> bool:
    s = line.strip()
    return s == "```" or s.startswith("```") and not s[3:].strip()


# ---------------------------------------------------------------------------
# A. File existence & encoding
# ---------------------------------------------------------------------------


def _check_files_exist() -> list[str]:
    errors = []
    for p, _label in [(EN_PATH, "EN"), (ZH_PATH, "ZH")]:
        if not p.exists():
            errors.append(f"Missing file: {p}")
    return errors


def _read_utf8(path: Path) -> tuple[str | None, list[str]]:
    """Return (text, errors)."""
    errors = []
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError as e:
        return None, [f"{path.name}: not valid UTF-8 — {e}"]
    # Check for U+FFFD
    if "�" in text:
        # Find line numbers
        for i, line in enumerate(text.splitlines(), 1):
            if "�" in line:
                errors.append(f"{path.name}:{i}: contains Unicode replacement character (U+FFFD)")
    # Check for mojibake fragments
    for frag in MOJIBAKE_FRAGMENTS:
        if frag in text:
            for i, line in enumerate(text.splitlines(), 1):
                if frag in line:
                    errors.append(f"{path.name}:{i}: possible mojibake fragment '{frag}'")
    return text, errors


# ---------------------------------------------------------------------------
# A2. Conflict marker detection (before any other text checks)
# ---------------------------------------------------------------------------

_CONFLICT_PATTERNS = ("<<<<<<<", "=======", ">>>>>>>")


def _check_conflict_markers(text: str, label: str) -> list[str]:
    """Detect Git conflict markers anywhere in the text."""
    errors = []
    for i, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        for pat in _CONFLICT_PATTERNS:
            if stripped.startswith(pat):
                errors.append(f"{label}:{i}: Git conflict marker found: '{stripped[:30]}'")
                break
    return errors


def _check_both_conflict_markers(en_text: str, zh_text: str) -> list[str]:
    """Check both READMEs for conflict markers."""
    errors = []
    errors.extend(_check_conflict_markers(en_text, "EN"))
    errors.extend(_check_conflict_markers(zh_text, "ZH"))
    return errors


# ---------------------------------------------------------------------------
# B. Sync section markers
# ---------------------------------------------------------------------------

_SYNC_RE = re.compile(r"<!--\s*(sync:\S+)\s*-->")


def _extract_sync_markers(text: str) -> list[str]:
    return _SYNC_RE.findall(text)


def _check_sync_markers(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_markers = _extract_sync_markers(en_text)
    zh_markers = _extract_sync_markers(zh_text)

    if len(en_markers) != len(zh_markers):
        errors.append(f"Sync marker count mismatch: EN={len(en_markers)}, ZH={len(zh_markers)}")

    for i, (em, zm) in enumerate(zip(en_markers, zh_markers, strict=False)):
        if em != zm:
            errors.append(f"Sync marker #{i+1} mismatch: EN='{em}' vs ZH='{zm}'")

    if len(en_markers) != len(set(en_markers)):
        dups = [m for m, c in Counter(en_markers).items() if c > 1]
        errors.append(f"Duplicate sync markers in EN: {dups}")
    if len(zh_markers) != len(set(zh_markers)):
        dups = [m for m, c in Counter(zh_markers).items() if c > 1]
        errors.append(f"Duplicate sync markers in ZH: {dups}")

    # Each marker must be followed by a heading (except NON_HEADING_MARKERS)
    for label, text in [("EN", en_text), ("ZH", zh_text)]:
        for marker in _extract_sync_markers(text):
            if marker in NON_HEADING_MARKERS:
                continue
            idx = text.find(f"<!-- {marker} -->")
            if idx == -1:
                idx = text.find(f"<!--{marker}-->")
            if idx == -1:
                continue
            after = text[idx : idx + 500]
            lines_after = after.splitlines()
            found_heading = False
            for line in lines_after[1:4]:
                if line.strip().startswith("#"):
                    found_heading = True
                    break
            if not found_heading:
                errors.append(f"{label}: sync marker '{marker}' not followed by a heading")

    return errors


# ---------------------------------------------------------------------------
# C. Heading structure
# ---------------------------------------------------------------------------

_HEADING_RE = re.compile(r"^(#{1,6})\s")


def _extract_heading_levels(text: str) -> list[int]:
    levels = []
    for line in text.splitlines():
        m = _HEADING_RE.match(line)
        if m:
            levels.append(len(m.group(1)))
    return levels


def _check_heading_structure(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_levels = _extract_heading_levels(en_text)
    zh_levels = _extract_heading_levels(zh_text)

    if len(en_levels) != len(zh_levels):
        errors.append(f"Heading count mismatch: EN={len(en_levels)}, ZH={len(zh_levels)}")

    for i, (el, zl) in enumerate(zip(en_levels, zh_levels, strict=False)):
        if el != zl:
            errors.append(f"Heading #{i+1} level mismatch: EN=H{el} vs ZH=H{zl}")

    return errors


# ---------------------------------------------------------------------------
# D. Images
# ---------------------------------------------------------------------------

_IMG_MD_RE = re.compile(r"!\[.*?\]\((.*?)\)")
_IMG_HTML_RE = re.compile(r'<img\s[^>]*src=["\']([^"\']+)["\']', re.IGNORECASE)


def _extract_image_paths(text: str) -> list[str]:
    paths = []
    for m in _IMG_MD_RE.finditer(text):
        paths.append(m.group(1))
    for m in _IMG_HTML_RE.finditer(text):
        paths.append(m.group(1))
    return paths


def _check_images(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_imgs = _extract_image_paths(en_text)
    zh_imgs = _extract_image_paths(zh_text)

    if len(en_imgs) != len(zh_imgs):
        errors.append(f"Image count mismatch: EN={len(en_imgs)}, ZH={len(zh_imgs)}")

    for i, (ei, zi) in enumerate(zip(en_imgs, zh_imgs, strict=False)):
        if ei != zi:
            errors.append(f"Image #{i+1} path mismatch: EN='{ei}' vs ZH='{zi}'")

    # Verify local images exist
    for label, paths in [("EN", en_imgs), ("ZH", zh_imgs)]:
        for p in paths:
            # Skip external URLs
            if p.startswith(("http://", "https://")):
                continue
            # Relative to project root
            full = PROJECT / p
            if not full.exists() and not (PROJECT / "docs" / p).exists():
                errors.append(f"{label}: referenced image not found: {p}")

    return errors


# ---------------------------------------------------------------------------
# E. Links
# ---------------------------------------------------------------------------

_LINK_RE = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)]*)\)")


def _extract_link_targets(text: str) -> list[str]:
    targets = []
    for m in _LINK_RE.finditer(text):
        targets.append(m.group(2))
    return targets


def _check_links(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_links = [ln for ln in _extract_link_targets(en_text) if ln not in LANGUAGE_LINKS]
    zh_links = [ln for ln in _extract_link_targets(zh_text) if ln not in LANGUAGE_LINKS]

    if len(en_links) != len(zh_links):
        errors.append(
            f"Link count mismatch (excl. language switch): EN={len(en_links)}, ZH={len(zh_links)}"
        )

    for i, (el, zl) in enumerate(zip(en_links, zh_links, strict=False)):
        if el != zl:
            errors.append(f"Link #{i+1} target mismatch: EN='{el}' vs ZH='{zl}'")

    return errors


# ---------------------------------------------------------------------------
# F. Fenced code blocks
# ---------------------------------------------------------------------------


def _extract_code_blocks(text: str) -> list[tuple[str, str]]:
    """Return list of (language_tag, content)."""
    blocks = []
    in_fence = False
    fence_lang = ""
    fence_lines: list[str] = []
    for line in text.splitlines():
        if not in_fence and _is_fence_opener(line):
            in_fence = True
            fence_lang = _fence_header(line)
            fence_lines = []
        elif in_fence and _is_fence_closer(line):
            in_fence = False
            content = "\n".join(fence_lines)
            blocks.append((fence_lang, content))
        elif in_fence:
            fence_lines.append(line)
    return blocks


def _check_code_blocks(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_blocks = _extract_code_blocks(en_text)
    zh_blocks = _extract_code_blocks(zh_text)

    if len(en_blocks) != len(zh_blocks):
        errors.append(f"Code block count mismatch: EN={len(en_blocks)}, ZH={len(zh_blocks)}")

    for i, (eb, zb) in enumerate(zip(en_blocks, zh_blocks, strict=False)):
        elang, econtent = eb
        zlang, zcontent = zb
        if elang != zlang:
            errors.append(f"Code block #{i+1} language tag mismatch: EN='{elang}' vs ZH='{zlang}'")
        if econtent != zcontent:
            # Find first differing line
            elines = econtent.splitlines()
            zlines = zcontent.splitlines()
            for j, (el, zl) in enumerate(zip(elines, zlines, strict=False)):
                if el != zl:
                    errors.append(
                        f"Code block #{i+1} content mismatch at line {j+1}:\n"
                        f"  EN: {el}\n  ZH: {zl}"
                    )
                    break
            else:
                if len(elines) != len(zlines):
                    errors.append(
                        f"Code block #{i+1} content line count mismatch: "
                        f"EN={len(elines)}, ZH={len(zlines)}"
                    )
                else:
                    errors.append(f"Code block #{i+1} content differs (whitespace only)")

    return errors


# ---------------------------------------------------------------------------
# G. Numeric facts (multiset of numeric tokens — visible text only)
# ---------------------------------------------------------------------------

_NUMERIC_TOKEN_RE = re.compile(r"\b(\d+(?:[.,]\d+)?%?|v\d+\.\d+\.\d+|portfolio-v\d+\.\d+\.\d+)\b")

# Patterns to strip before extracting numeric facts
# Order matters: remove images before links (badges are images nested inside links)
_STRIP_CODE_BLOCKS = re.compile(r"```.*?```", flags=re.DOTALL)
_STRIP_IMG_HTML = re.compile(r"<img[^>]*>", flags=re.IGNORECASE)
_STRIP_IMG_MD = re.compile(r"!\[[^\]]*\]\([^)]*\)")
_STRIP_LINK_MD = re.compile(r"\[([^\]]*)\]\([^)]*\)")
_STRIP_HTML_TAGS = re.compile(r"<[^>]+>")


def _strip_non_visible_syntax(text: str) -> str:
    """Remove markdown/image/link/HTML syntax so only visible prose remains.

    This ensures numeric tokens are extracted from visible prose, table cells,
    headings, and captions — NOT from badge URLs, image URLs, link targets,
    or HTML attributes.  It deliberately strips image alt text as well, since
    alt text is an image-level concern already covered by the image-path check.
    """
    # 1. Remove fenced code blocks (they are checked separately)
    cleaned = _STRIP_CODE_BLOCKS.sub("", text)
    # 2. Remove HTML image tags completely
    cleaned = _STRIP_IMG_HTML.sub("", cleaned)
    # 3. Remove Markdown images ![alt](url) completely
    cleaned = _STRIP_IMG_MD.sub("", cleaned)
    # 4. Replace [text](url) with just the visible link text (keep text, drop URL)
    cleaned = _STRIP_LINK_MD.sub(r"\1", cleaned)
    # 5. Remove remaining HTML tags
    cleaned = _STRIP_HTML_TAGS.sub("", cleaned)
    # 6. Remove language-switch link remnants
    for ll in LANGUAGE_LINKS:
        cleaned = cleaned.replace(ll, "")
    return cleaned


def _extract_numeric_tokens(text: str) -> Counter:
    """Extract numeric tokens as a multiset from *visible* prose only.

    Badge URLs, image URLs, link targets, and HTML src/href attributes are
    stripped before extraction so they cannot produce spurious tokens like
    ``20``, ``20406``, ``2041``, or ``2044`` from URL-encoded badge text.
    """
    cleaned = _strip_non_visible_syntax(text)
    tokens = _NUMERIC_TOKEN_RE.findall(cleaned)
    return Counter(tokens)


def _check_numeric_facts(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_nums = _extract_numeric_tokens(en_text)
    zh_nums = _extract_numeric_tokens(zh_text)

    en_set = set(en_nums.keys())
    zh_set = set(zh_nums.keys())
    only_en = en_set - zh_set
    only_zh = zh_set - en_set
    if only_en:
        errors.append(f"Numeric tokens only in EN: {sorted(only_en)}")
    if only_zh:
        errors.append(f"Numeric tokens only in ZH: {sorted(only_zh)}")

    for token in en_set & zh_set:
        if en_nums[token] != zh_nums[token]:
            errors.append(
                f"Numeric token '{token}' count mismatch: EN={en_nums[token]}, ZH={zh_nums[token]}"
            )

    return errors


# ---------------------------------------------------------------------------
# H. Markdown tables
# ---------------------------------------------------------------------------

_TABLE_SEP_RE = re.compile(r"^\s*\|?[\s\-:]+\|[\s\-:|]+\s*$")


def _extract_tables(text: str) -> list[list[list[str]]]:
    """Return list of tables, each table = list of rows, each row = list of cells."""
    tables = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        # Find table: header line followed by separator line
        line = lines[i].strip()
        if "|" in line and i + 1 < len(lines) and _TABLE_SEP_RE.match(lines[i + 1].strip()):
            table = []
            # Header row
            header_cells = [c.strip() for c in line.split("|")]
            header_cells = [
                c
                for c in header_cells
                if c or header_cells.index(c) not in (0, len(header_cells) - 1)
            ]
            # If first/last are empty, they're table border
            table.append(header_cells)
            i += 2  # skip separator
            # Data rows
            while i < len(lines) and "|" in lines[i]:
                row_cells = [c.strip() for c in lines[i].split("|")]
                table.append(row_cells)
                i += 1
            if len(table) > 1:  # At least header + one data row
                tables.append(table)
        else:
            i += 1
    return tables


def _check_tables(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_tables = _extract_tables(en_text)
    zh_tables = _extract_tables(zh_text)

    if len(en_tables) != len(zh_tables):
        errors.append(f"Table count mismatch: EN={len(en_tables)}, ZH={len(zh_tables)}")

    for ti, (et, zt) in enumerate(zip(en_tables, zh_tables, strict=False)):
        if len(et) != len(zt):
            errors.append(f"Table #{ti+1} row count mismatch: EN={len(et)}, ZH={len(zt)}")
        if et and zt and len(et[0]) != len(zt[0]):
            errors.append(f"Table #{ti+1} column count mismatch: EN={len(et[0])}, ZH={len(zt[0])}")
        # Compare cells that contain numeric tokens — the numeric parts must match
        for ri, (er, zr) in enumerate(zip(et, zt, strict=False)):
            for ci, (ec, zc) in enumerate(zip(er, zr, strict=False)):
                en_nums = _NUMERIC_TOKEN_RE.findall(ec)
                zh_nums = _NUMERIC_TOKEN_RE.findall(zc)
                if en_nums or zh_nums:
                    if en_nums != zh_nums:
                        errors.append(
                            f"Table #{ti+1}, row {ri}, col {ci}: "
                            f"numeric token mismatch: EN='{ec}' ({en_nums}) vs ZH='{zc}' ({zh_nums})"
                        )

    return errors


# ---------------------------------------------------------------------------
# I. Badges
# ---------------------------------------------------------------------------

_BADGE_IMG_RE = re.compile(r"!\[([^\]]*)\]\((https://img\.shields\.io[^)]+)\)")
_BADGE_LINK_RE = re.compile(r"\[!\[.*?\]\(https://img\.shields\.io[^)]+\)\]\(([^)]+)\)")


def _check_badges(en_text: str, zh_text: str) -> list[str]:
    errors = []
    en_badge_imgs = [m.group(2) for m in _BADGE_IMG_RE.finditer(en_text)]
    zh_badge_imgs = [m.group(2) for m in _BADGE_IMG_RE.finditer(zh_text)]
    en_badge_links = _BADGE_LINK_RE.findall(en_text)
    zh_badge_links = _BADGE_LINK_RE.findall(zh_text)

    if en_badge_imgs != zh_badge_imgs:
        errors.append(
            f"Badge images mismatch: EN has {len(en_badge_imgs)}, ZH has {len(zh_badge_imgs)}"
        )
        for i, (ei, zi) in enumerate(zip(en_badge_imgs, zh_badge_imgs, strict=False)):
            if ei != zi:
                errors.append(f"Badge #{i+1} image URL mismatch: EN='{ei}' vs ZH='{zi}'")

    if en_badge_links != zh_badge_links:
        errors.append("Badge link targets mismatch")
        for i, (el, zl) in enumerate(zip(en_badge_links, zh_badge_links, strict=False)):
            if el != zl:
                errors.append(f"Badge #{i+1} link target mismatch: EN='{el}' vs ZH='{zl}'")

    return errors


# ---------------------------------------------------------------------------
# J. Absolute path check
# ---------------------------------------------------------------------------

_ABS_PATH_RE = re.compile(r"(?:[A-Za-z]:\\|" + chr(47)+"home"+chr(47) + r"|/Users/)")


def _check_no_absolute_paths(en_text: str, zh_text: str) -> list[str]:
    errors = []
    for label, text in [("EN", en_text), ("ZH", zh_text)]:
        for m in _ABS_PATH_RE.finditer(text):
            ctx_start = max(0, m.start() - 20)
            ctx_end = min(len(text), m.end() + 40)
            ctx = text[ctx_start:ctx_end].replace("\n", "\\n")
            errors.append(f"{label}: absolute path found near: ...{ctx}...")
    return errors


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

_SECTION_CHECKS = [
    ("file existence & encoding", lambda en, zh: _check_files_exist()),
    (
        "encoding & mojibake",
        lambda en, zh: _read_utf8(EN_PATH)[1] + _read_utf8(ZH_PATH)[1],
    ),
    ("conflict markers", _check_both_conflict_markers),
    ("sync markers", _check_sync_markers),
    ("heading structure", _check_heading_structure),
    ("images", _check_images),
    ("links", _check_links),
    ("code blocks", _check_code_blocks),
    ("numeric facts", _check_numeric_facts),
    ("tables", _check_tables),
    ("badges", _check_badges),
    ("absolute paths", _check_no_absolute_paths),
]


def main() -> int:
    all_errors: list[str] = []

    # Read both files
    en_text, en_errs = _read_utf8(EN_PATH)
    zh_text, zh_errs = _read_utf8(ZH_PATH)
    all_errors.extend(en_errs)
    all_errors.extend(zh_errs)

    if en_text is None or zh_text is None:
        for e in all_errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    # Run all text-based checks
    results: dict[str, bool] = {}
    for name, check_fn in _SECTION_CHECKS:
        if check_fn.__code__.co_argcount == 0:
            errs = check_fn()  # type: ignore[call-arg]
        else:
            errs = check_fn(en_text, zh_text)
        all_errors.extend(errs)
        results[name] = len(errs) == 0
        status = "PASS" if len(errs) == 0 else f"FAIL ({len(errs)} issue(s))"
        print(f"  {name:30s}  {status}")

    if all_errors:
        print("\n--- DETAILS ---", file=sys.stderr)
        for e in all_errors:
            print(f"  ERROR: {e}", file=sys.stderr)
        print("\nBILINGUAL_README_CONSISTENCY_FAILED", file=sys.stderr)
        return 1

    print("\nBILINGUAL_README_CONSISTENCY_PASSED")
    print(f"  sections checked: {len(results)}")
    print(f"  headings checked: {len(_extract_heading_levels(en_text))}")
    print(f"  images checked: {len(_extract_image_paths(en_text))}")
    print(
        f"  links checked: {len([ln for ln in _extract_link_targets(en_text) if ln not in LANGUAGE_LINKS])}"
    )
    print(f"  code blocks checked: {len(_extract_code_blocks(en_text))}")
    print(f"  tables checked: {len(_extract_tables(en_text))}")
    print(f"  numeric facts checked: {len(_extract_numeric_tokens(en_text))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
